---
# See https://pre-commit.com for more information
default_language_version:
  python: python3.9

# This section is solely for pre-commit.ci. See https://pre-commit.ci/#configuration
ci:
    # Do not run the pip-compile hook when in CI
    # See https://github.com/pre-commit-ci/issues/issues/133#issuecomment-1172964243
    skip: [pip-compile]

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '(notebooks|attic|benchmark|testdata)/.*'
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args:
          - '--maxkb=1024'
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    - id: ruff-format
      exclude: '(notebooks|attic|benchmark|testdata|gui)/.*'
    - id: ruff
      exclude: '(notebooks|attic|benchmark|testdata|gui)/.*'
      alias: autoformat
      args:
        - '--fix'
        - '--exit-non-zero-on-fix'
        - '--ignore=E741,E501,PD901,F841,B007,E741,B028,F811'
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        args:
          - 'pyproject.toml'
          - '--all-extras'
          - '--resolver=backtracking'
          - '--output-file=requirements.txt'
          - '--no-strip-extras'
          - '--quiet'
          - '--no-emit-trusted-host'
